import type { KanaEntry, Settings } from "./types.ts";

function h(kana: string, readings: readonly string[], group: "gojuon" | "dakuten" | "combo"): KanaEntry {
  return { kana, readings, group, set: "hiragana" };
}

function k(kana: string, readings: readonly string[], group: "gojuon" | "dakuten" | "combo"): KanaEntry {
  return { kana, readings, group, set: "katakana" };
}

const hiragana: readonly KanaEntry[] = [
  // Gojuon (46)
  h("あ", ["a"], "gojuon"),
  h("い", ["i"], "gojuon"),
  h("う", ["u"], "gojuon"),
  h("え", ["e"], "gojuon"),
  h("お", ["o"], "gojuon"),
  h("か", ["ka"], "gojuon"),
  h("き", ["ki"], "gojuon"),
  h("く", ["ku"], "gojuon"),
  h("け", ["ke"], "gojuon"),
  h("こ", ["ko"], "gojuon"),
  h("さ", ["sa"], "gojuon"),
  h("し", ["shi", "si"], "gojuon"),
  h("す", ["su"], "gojuon"),
  h("せ", ["se"], "gojuon"),
  h("そ", ["so"], "gojuon"),
  h("た", ["ta"], "gojuon"),
  h("ち", ["chi", "ti"], "gojuon"),
  h("つ", ["tsu", "tu"], "gojuon"),
  h("て", ["te"], "gojuon"),
  h("と", ["to"], "gojuon"),
  h("な", ["na"], "gojuon"),
  h("に", ["ni"], "gojuon"),
  h("ぬ", ["nu"], "gojuon"),
  h("ね", ["ne"], "gojuon"),
  h("の", ["no"], "gojuon"),
  h("は", ["ha"], "gojuon"),
  h("ひ", ["hi"], "gojuon"),
  h("ふ", ["fu", "hu"], "gojuon"),
  h("へ", ["he"], "gojuon"),
  h("ほ", ["ho"], "gojuon"),
  h("ま", ["ma"], "gojuon"),
  h("み", ["mi"], "gojuon"),
  h("む", ["mu"], "gojuon"),
  h("め", ["me"], "gojuon"),
  h("も", ["mo"], "gojuon"),
  h("や", ["ya"], "gojuon"),
  h("ゆ", ["yu"], "gojuon"),
  h("よ", ["yo"], "gojuon"),
  h("ら", ["ra"], "gojuon"),
  h("り", ["ri"], "gojuon"),
  h("る", ["ru"], "gojuon"),
  h("れ", ["re"], "gojuon"),
  h("ろ", ["ro"], "gojuon"),
  h("わ", ["wa"], "gojuon"),
  h("を", ["wo", "o"], "gojuon"),
  h("ん", ["n"], "gojuon"),

  // Dakuten (25)
  h("が", ["ga"], "dakuten"),
  h("ぎ", ["gi"], "dakuten"),
  h("ぐ", ["gu"], "dakuten"),
  h("げ", ["ge"], "dakuten"),
  h("ご", ["go"], "dakuten"),
  h("ざ", ["za"], "dakuten"),
  h("じ", ["ji", "zi"], "dakuten"),
  h("ず", ["zu"], "dakuten"),
  h("ぜ", ["ze"], "dakuten"),
  h("ぞ", ["zo"], "dakuten"),
  h("だ", ["da"], "dakuten"),
  h("ぢ", ["di", "ji", "dzi"], "dakuten"),
  h("づ", ["du", "zu", "dzu"], "dakuten"),
  h("で", ["de"], "dakuten"),
  h("ど", ["do"], "dakuten"),
  h("ば", ["ba"], "dakuten"),
  h("び", ["bi"], "dakuten"),
  h("ぶ", ["bu"], "dakuten"),
  h("べ", ["be"], "dakuten"),
  h("ぼ", ["bo"], "dakuten"),
  h("ぱ", ["pa"], "dakuten"),
  h("ぴ", ["pi"], "dakuten"),
  h("ぷ", ["pu"], "dakuten"),
  h("ぺ", ["pe"], "dakuten"),
  h("ぽ", ["po"], "dakuten"),

  // Combo/yoon (33)
  h("きゃ", ["kya"], "combo"),
  h("きゅ", ["kyu"], "combo"),
  h("きょ", ["kyo"], "combo"),
  h("しゃ", ["sha", "sya"], "combo"),
  h("しゅ", ["shu", "syu"], "combo"),
  h("しょ", ["sho", "syo"], "combo"),
  h("ちゃ", ["cha", "tya"], "combo"),
  h("ちゅ", ["chu", "tyu"], "combo"),
  h("ちょ", ["cho", "tyo"], "combo"),
  h("にゃ", ["nya"], "combo"),
  h("にゅ", ["nyu"], "combo"),
  h("にょ", ["nyo"], "combo"),
  h("ひゃ", ["hya"], "combo"),
  h("ひゅ", ["hyu"], "combo"),
  h("ひょ", ["hyo"], "combo"),
  h("みゃ", ["mya"], "combo"),
  h("みゅ", ["myu"], "combo"),
  h("みょ", ["myo"], "combo"),
  h("りゃ", ["rya"], "combo"),
  h("りゅ", ["ryu"], "combo"),
  h("りょ", ["ryo"], "combo"),
  h("ぎゃ", ["gya"], "combo"),
  h("ぎゅ", ["gyu"], "combo"),
  h("ぎょ", ["gyo"], "combo"),
  h("じゃ", ["ja", "jya", "zya"], "combo"),
  h("じゅ", ["ju", "jyu", "zyu"], "combo"),
  h("じょ", ["jo", "jyo", "zyo"], "combo"),
  h("びゃ", ["bya"], "combo"),
  h("びゅ", ["byu"], "combo"),
  h("びょ", ["byo"], "combo"),
  h("ぴゃ", ["pya"], "combo"),
  h("ぴゅ", ["pyu"], "combo"),
  h("ぴょ", ["pyo"], "combo"),
];

const katakana: readonly KanaEntry[] = [
  // Gojuon (46)
  k("ア", ["a"], "gojuon"),
  k("イ", ["i"], "gojuon"),
  k("ウ", ["u"], "gojuon"),
  k("エ", ["e"], "gojuon"),
  k("オ", ["o"], "gojuon"),
  k("カ", ["ka"], "gojuon"),
  k("キ", ["ki"], "gojuon"),
  k("ク", ["ku"], "gojuon"),
  k("ケ", ["ke"], "gojuon"),
  k("コ", ["ko"], "gojuon"),
  k("サ", ["sa"], "gojuon"),
  k("シ", ["shi", "si"], "gojuon"),
  k("ス", ["su"], "gojuon"),
  k("セ", ["se"], "gojuon"),
  k("ソ", ["so"], "gojuon"),
  k("タ", ["ta"], "gojuon"),
  k("チ", ["chi", "ti"], "gojuon"),
  k("ツ", ["tsu", "tu"], "gojuon"),
  k("テ", ["te"], "gojuon"),
  k("ト", ["to"], "gojuon"),
  k("ナ", ["na"], "gojuon"),
  k("ニ", ["ni"], "gojuon"),
  k("ヌ", ["nu"], "gojuon"),
  k("ネ", ["ne"], "gojuon"),
  k("ノ", ["no"], "gojuon"),
  k("ハ", ["ha"], "gojuon"),
  k("ヒ", ["hi"], "gojuon"),
  k("フ", ["fu", "hu"], "gojuon"),
  k("ヘ", ["he"], "gojuon"),
  k("ホ", ["ho"], "gojuon"),
  k("マ", ["ma"], "gojuon"),
  k("ミ", ["mi"], "gojuon"),
  k("ム", ["mu"], "gojuon"),
  k("メ", ["me"], "gojuon"),
  k("モ", ["mo"], "gojuon"),
  k("ヤ", ["ya"], "gojuon"),
  k("ユ", ["yu"], "gojuon"),
  k("ヨ", ["yo"], "gojuon"),
  k("ラ", ["ra"], "gojuon"),
  k("リ", ["ri"], "gojuon"),
  k("ル", ["ru"], "gojuon"),
  k("レ", ["re"], "gojuon"),
  k("ロ", ["ro"], "gojuon"),
  k("ワ", ["wa"], "gojuon"),
  k("ヲ", ["wo", "o"], "gojuon"),
  k("ン", ["n"], "gojuon"),

  // Dakuten (25)
  k("ガ", ["ga"], "dakuten"),
  k("ギ", ["gi"], "dakuten"),
  k("グ", ["gu"], "dakuten"),
  k("ゲ", ["ge"], "dakuten"),
  k("ゴ", ["go"], "dakuten"),
  k("ザ", ["za"], "dakuten"),
  k("ジ", ["ji", "zi"], "dakuten"),
  k("ズ", ["zu"], "dakuten"),
  k("ゼ", ["ze"], "dakuten"),
  k("ゾ", ["zo"], "dakuten"),
  k("ダ", ["da"], "dakuten"),
  k("ヂ", ["di", "ji", "dzi"], "dakuten"),
  k("ヅ", ["du", "zu", "dzu"], "dakuten"),
  k("デ", ["de"], "dakuten"),
  k("ド", ["do"], "dakuten"),
  k("バ", ["ba"], "dakuten"),
  k("ビ", ["bi"], "dakuten"),
  k("ブ", ["bu"], "dakuten"),
  k("ベ", ["be"], "dakuten"),
  k("ボ", ["bo"], "dakuten"),
  k("パ", ["pa"], "dakuten"),
  k("ピ", ["pi"], "dakuten"),
  k("プ", ["pu"], "dakuten"),
  k("ペ", ["pe"], "dakuten"),
  k("ポ", ["po"], "dakuten"),

  // Combo/yoon (33)
  k("キャ", ["kya"], "combo"),
  k("キュ", ["kyu"], "combo"),
  k("キョ", ["kyo"], "combo"),
  k("シャ", ["sha", "sya"], "combo"),
  k("シュ", ["shu", "syu"], "combo"),
  k("ショ", ["sho", "syo"], "combo"),
  k("チャ", ["cha", "tya"], "combo"),
  k("チュ", ["chu", "tyu"], "combo"),
  k("チョ", ["cho", "tyo"], "combo"),
  k("ニャ", ["nya"], "combo"),
  k("ニュ", ["nyu"], "combo"),
  k("ニョ", ["nyo"], "combo"),
  k("ヒャ", ["hya"], "combo"),
  k("ヒュ", ["hyu"], "combo"),
  k("ヒョ", ["hyo"], "combo"),
  k("ミャ", ["mya"], "combo"),
  k("ミュ", ["myu"], "combo"),
  k("ミョ", ["myo"], "combo"),
  k("リャ", ["rya"], "combo"),
  k("リュ", ["ryu"], "combo"),
  k("リョ", ["ryo"], "combo"),
  k("ギャ", ["gya"], "combo"),
  k("ギュ", ["gyu"], "combo"),
  k("ギョ", ["gyo"], "combo"),
  k("ジャ", ["ja", "jya", "zya"], "combo"),
  k("ジュ", ["ju", "jyu", "zyu"], "combo"),
  k("ジョ", ["jo", "jyo", "zyo"], "combo"),
  k("ビャ", ["bya"], "combo"),
  k("ビュ", ["byu"], "combo"),
  k("ビョ", ["byo"], "combo"),
  k("ピャ", ["pya"], "combo"),
  k("ピュ", ["pyu"], "combo"),
  k("ピョ", ["pyo"], "combo"),
];

export const KANA: readonly KanaEntry[] = [...hiragana, ...katakana];

export function getActiveKana(settings: Settings): readonly KanaEntry[] {
  const result: KanaEntry[] = [];
  if (settings.hiragana) {
    result.push(...hiragana);
  }
  if (settings.katakana) {
    result.push(...katakana);
  }
  return result;
}
